# Generated by Django 2.2.5 on 2020-05-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200513_2333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='post/images/', verbose_name='Image', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.PositiveIntegerField(default=400, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.PositiveIntegerField(default=400, verbose_name='Image Width'),
        ),
    ]
