# Generated by Django 2.2.5 on 2020-05-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200516_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='image_height', upload_to='post/images/', verbose_name='Image', width_field='image_width'),
        ),
    ]
