# Generated by Django 2.2.5 on 2020-05-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200516_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
    ]
